version: "3.8"

services:
  app:
    build: ./app
    container_name: ml_app
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - database
      - rabbitmq
    restart: always

  web-proxy:
    build: ./nginx
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - .env
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always

  database:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
