version: "3.8"

services:
  app:
    build: ./app
    container_name: ml_app
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./models:/app/models
    ports:
    - "8082:8080"
    depends_on:
      - database
      - rabbitmq
    restart: on-failure

  web-proxy:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - .env
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: on-failure

  database:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    expose:
      - 5432
    restart: unless-stopped
